name       : python-toolz
version    : 0.12.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/toolz/toolz-0.12.0.tar.gz : 88c570861c440ee3f2f6037c4654613228ff40c93a6c25e0eba70d17282c6194
license    : BSD-3-Clause
homepage   : https://github.com/pytoolz/toolz/
component  : programming.python
summary    : A functional standard library for Python
description: |
    A set of utility functions for iterators, functions, and dictionaries for Python
build      : |
    %python3_setup
install    : |
    %python3_install
